---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: arangodb
data:
  {{ $dbpass := .Values.arangodb_pass | default "" }}
  {{ $dbuser := .Values.arangodb_user | default "root" }}
  {{ $dbhost := .Values.arangodb_host | default "localhost" }}
  {{ $dbport := .Values.arangodb_port | default "8529" }}
  {{ $dbname := .Values.arangodb_name | default "ortelius" }}
  DBPassword: {{ $dbpass | b64enc }}
  DBUserName: {{ $dbuser | b64enc }}
  {{ if (((.Values.global).arangodb).enabled) }}
  DBHost:  {{ printf "ms-arangodb.%s.svc.cluster.local" .Release.Namespace | b64enc  }}
  {{ else }}
  DBHost: {{ $dbhost | b64enc }}
  {{ end }}
  DBPort: {{ $dbport | b64enc }}
  DBName: {{ $dbname | b64enc }}
