basePath: /msapi/deppkg
host: localhost:3000
info:
  contact:
    email: ortelius-dev@googlegroups.com
    name: Ortelius Google Group
  description: |-
    RestAPI for the deppkg Object
    ![Release](https://img.shields.io/github/v/release/ortelius/scec-deppkg?sort=semver)
    ![license](https://img.shields.io/github/license/ortelius/scec-deppkg)

    ![Build](https://img.shields.io/github/actions/workflow/status/ortelius/scec-deppkg/build-push-chart.yml)
    [![MegaLinter](https://github.com/ortelius/scec-deppkg/workflows/MegaLinter/badge.svg?branch=main)](https://github.com/ortelius/scec-deppkg/actions?query=workflow%3AMegaLinter+branch%3Amain)
    ![CodeQL](https://github.com/ortelius/scec-deppkg/workflows/CodeQL/badge.svg)
    [![OpenSSF-Scorecard](https://api.securityscorecards.dev/projects/github.com/ortelius/scec-deppkg/badge)](https://api.securityscorecards.dev/projects/github.com/ortelius/scec-deppkg)

    ![Discord](https://img.shields.io/discord/722468819091849316)
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Ortelius v11 DepPkg Microservice
  version: 11.0.0
paths:
  /msapi/deppkg:
    get:
      consumes:
        - "*/*"
      description: Get a list of DepPkgs.
      produces:
        - application/json
      responses:
        "200":
          description: OK
      summary: Get a List of DepPkgs
      tags:
        - DepPkgs
    post:
      consumes:
        - application/json
        - DepPkgs
    post:
      consumes:
        - application/json
      description: Create a new DepPkg and persist it
      produces:
        - application/json
      responses:
        "200":
          description: OK
      summary: Create a DepPkg
      tags:
        - deppkg
  /msapi/deppkg/:key:
    get:
      consumes:
        - "*/*"
      - deppkg
  /msapi/deppkg/:key:
    get:
      consumes:
      - '*/*'
        - deppkg
  /msapi/deppkg/:key:
    get:
      consumes:
        - "*/*"
      description: Get a deppkg based on the _key or name.
      produces:
        - application/json
      responses:
        "200":
          description: OK
      summary: Get a DepPkg
      tags:
      - deppkg
swagger: "2.0"
